# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(944, 831)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(30, 140, 201, 411))
        self.groupBox.setObjectName("groupBox")
        self.connbtn = QtWidgets.QPushButton(self.groupBox)
        self.connbtn.setGeometry(QtCore.QRect(40, 40, 121, 41))
        self.connbtn.setObjectName("connbtn")
        self.video_2 = QtWidgets.QPushButton(self.groupBox)
        self.video_2.setGeometry(QtCore.QRect(40, 100, 121, 41))
        self.video_2.setObjectName("video_2")
        self.luxiang = QtWidgets.QPushButton(self.groupBox)
        self.luxiang.setGeometry(QtCore.QRect(40, 160, 121, 41))
        self.luxiang.setObjectName("luxiang")
        self.image_det = QtWidgets.QPushButton(self.groupBox)
        self.image_det.setGeometry(QtCore.QRect(40, 220, 121, 41))
        self.image_det.setObjectName("image_det")
        self.video_det = QtWidgets.QPushButton(self.groupBox)
        self.video_det.setGeometry(QtCore.QRect(40, 280, 121, 41))
        self.video_det.setObjectName("video_det")
        self.close = QtWidgets.QPushButton(self.groupBox)
        self.close.setGeometry(QtCore.QRect(40, 340, 121, 41))
        self.close.setObjectName("close")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(260, 40, 671, 751))
        self.groupBox_2.setObjectName("groupBox_2")
        self.video = QtWidgets.QLabel(self.groupBox_2)
        self.video.setGeometry(QtCore.QRect(20, 60, 641, 651))
        self.video.setAlignment(QtCore.Qt.AlignCenter)
        self.video.setObjectName("video")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 40, 201, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(10, 30, 181, 51))
        self.label.setStyleSheet("font: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 255), stop:0.495 rgba(255, 255, 255, 255), stop:0.505 rgba(255, 0, 0, 255), stop:1 rgba(255, 0, 0, 255));\n"
"font: rgb(255, 255, 255);\n"
"font: 75 14pt \"Ubuntu Condensed\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(30, 590, 201, 80))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 199, 78))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.zhuangtai = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.zhuangtai.setGeometry(QtCore.QRect(10, 10, 181, 61))
        self.zhuangtai.setAlignment(QtCore.Qt.AlignCenter)
        self.zhuangtai.setObjectName("zhuangtai")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QtWidgets.QScrollArea(Form)
        self.scrollArea_2.setGeometry(QtCore.QRect(30, 700, 201, 80))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 199, 78))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 181, 61))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "操作区"))
        self.connbtn.setText(_translate("Form", "开启通信"))
        self.video_2.setText(_translate("Form", "打开摄像头"))
        self.luxiang.setText(_translate("Form", "开始录像"))
        self.image_det.setText(_translate("Form", "图片检测"))
        self.video_det.setText(_translate("Form", "视频检测"))
        self.close.setText(_translate("Form", "退出"))
        self.groupBox_2.setTitle(_translate("Form", "展示区"))
        self.video.setText(_translate("Form", "视频"))
        self.groupBox_3.setTitle(_translate("Form", "跌倒预警"))
        self.label.setText(_translate("Form", "无跌倒目标"))
        self.zhuangtai.setText(_translate("Form", "状态"))
        self.label_4.setText(_translate("Form", "视频状态"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
